### ISSUE TITLE
UI/UX Suggested Improvements

### ISSUE THREAD

**Issue by cgorringe** [internetarchive/wayback-machine-chrome#600]
Listing improvements to make in UI/UX based on initial user feedback:

- [x] Return to treating web.archive.org URLs as a special case, and using the extracted URL to act on. (#603)

- [x] When the Search Box isn't empty, use that domain as the URL to act on instead of the web browser's address bar. (#607)

- [x] Add Tooltips to Outlinks and Screenshot options.

- [x] Group Outlinks and Screenshots by drawing a frame around them and "Save Page Now" button to show that they're linked. (#605)

- [x] Users expect "URL not supported" message to go away when they enter something in Search box. (#606)

- [ ] When the user is prompted to the 'Login' page, save the page after successful login. (**may skip**)

**Comment by anishsarangi** [comment]
@cgorringe I will take care of the last check box ! Thank you !
